language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

os:
    - linux

env:
    global:
        - PYTHON_VERSION=2.7
        - NUMPY_VERSION=1.10
        - ASTROPY_VERSION=stable
        - PIP_DEPENDENCIES=''
        - CONDA_DEPENDENCIES='ipython ipython-notebook runipy matplotlib scipy h5py pyyaml beautifulsoup4'
        - GH_REF: github.com/astropy/astropy-tutorials.git
        - secure: "NBZlEg//sDYvJikqXESLsx/WA1Nj7fAH2mJfI8ZVMnolvyjJuLdEMxxEYFP8t6U/iieSSrgUkgP94yy5Oq6iJRjj7ThGCdcjgvgWTQCzoQgEVDc5SzdJGyGs30VC+8t7GTobzMe086HX16SJRvsIumqXdmRcJjAdMCyhMUxLoUg="

before_install:
    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - python prepare_deploy.py run

deploy:
    provider: script
    script: ./travis_deploy
    on:
        repo: astropy/astropy-tutorials
        branch: master